# Generated by Django 5.2.12 on 2026-04-15 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='postreport',
            new_name='api_post_re_post_id_8b4954_idx',
            old_name='api_postreport_post_idx',
        ),
        migrations.RenameIndex(
            model_name='postreport',
            new_name='api_post_re_status_1d6532_idx',
            old_name='api_postreport_status_idx',
        ),
    ]
