# Generated by Django 5.2.12 on 2026-03-31 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_forum_section_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='is_visible',
        ),
        migrations.AddField(
            model_name='forum',
            name='access_level',
            field=models.SmallIntegerField(choices=[(0, 'Public'), (1, 'Registered only'), (2, 'Admin only')], default=0, help_text='Who can see this forum (phpBB visibility_class)'),
        ),
        migrations.AddField(
            model_name='forum',
            name='archive_level',
            field=models.SmallIntegerField(choices=[(0, 'Normal'), (1, 'Soft darkweb (spam=1 users)'), (2, 'Hard darkweb (Krowa clones, Więzienie etc.)')], default=0, help_text='Archive content sensitivity level'),
        ),
        migrations.AddField(
            model_name='user',
            name='archive_access',
            field=models.SmallIntegerField(default=0, help_text='Max archive_level user can see: 0=normal, 1=soft darkweb, 2=hard darkweb (admin-granted)'),
        ),
    ]
