# Generated by Django 5.2.12 on 2026-03-31 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_remove_forum_is_visible_forum_access_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_ghost',
            field=models.BooleanField(default=False, help_text='Archive-imported account — no password, cannot log in'),
        ),
    ]
