# Generated by Django 5.2.12 on 2026-03-31 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_user_is_ghost'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_hash',
            field=models.CharField(blank=True, default='', help_text='Argon2 hash of normalised email — used for password reset', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='email_mask',
            field=models.CharField(blank=True, default='', help_text='Display mask, e.g. j***i@gmail.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, default='', editable=False, max_length=254),
        ),
    ]
