# Generated by Django 5.2.12 on 2026-04-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('board', '0006_activationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_root',
            field=models.BooleanField(default=False, help_text='Superadmin: manages users and forum structure. Cannot post, has no email, no password reset.'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('is_root', True)), fields=('is_root',), name='only_one_root'),
        ),
    ]
