# Generated by Django 5.2.12 on 2026-04-02 14:10

import board.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_post_created_at_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='spam_class',
            field=models.SmallIntegerField(choices=[(0, 'Normalny'), (1, 'Gray (zaśmiecacz)'), (2, 'Web (bot/spam rejestracyjny)')], db_index=True, default=0, help_text='Klasa spamu: 0=normalny, 1=gray, 2=web. Używana przez PLONK do filtrowania.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[board.models.validate_avatar]),
        ),
    ]
