# Generated by Django 5.2.12 on 2026-04-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_user_spam_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='TorExitNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True, unique=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'forum_tor_exit_nodes',
            },
        ),
    ]
