# Generated by Django 5.2.12 on 2026-04-02 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0011_blocked_ips'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockedip',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Null = permanentny ban. Ustawiany automatycznie na podstawie is_dangerous.', null=True),
        ),
        migrations.AddField(
            model_name='blockedip',
            name='is_dangerous',
            field=models.BooleanField(default=False, help_text='Groźne IP (np. celowy atak) — dłuższy czas blokady.'),
        ),
        migrations.AddField(
            model_name='post',
            name='author_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
