# Generated by Django 5.2.12 on 2026-04-02 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0012_ip_ban_expiry_and_post_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockedip',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='blockedip',
            name='is_dangerous',
        ),
        migrations.AddField(
            model_name='post',
            name='ip_flagged',
            field=models.BooleanField(default=False, help_text='Moderator oznaczył post jako groźny — dłuższa retencja IP.'),
        ),
        migrations.AddField(
            model_name='post',
            name='ip_retain_until',
            field=models.DateTimeField(blank=True, help_text='IP kasowane po tej dacie. Ustawiane przy tworzeniu posta.', null=True),
        ),
    ]
