# Generated by Django 5.2.12 on 2026-04-03 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0013_ip_retention_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content_html',
        ),
    ]
