# Generated by Django 5.2.12 on 2026-04-03 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0014_drop_content_html'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_hash',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_mask',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
