# Generated by Django 5.2.12 on 2026-04-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0015_plaintext_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username_normalized',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Lowercase, no diacritics, alphanumeric only. Used for uniqueness checks.', max_length=150),
        ),
    ]
