# Generated by Django 5.2.12 on 2026-04-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0020_post_broken_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reset_mode', models.CharField(choices=[('email', 'Wyślij emailem'), ('popup', 'Pokaż w oknie (tryb testowy)')], default='email', max_length=10)),
                ('show_switch_link', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'forum_siteconfig',
            },
        ),
        migrations.RemoveConstraint(
            model_name='privatemessagebox',
            name='unique_pm_box_per_user',
        ),
        migrations.RenameIndex(
            model_name='privatemessagebox',
            new_name='forum_pm_bo_owner_i_f822fd_idx',
            old_name='pm_box_owner_type_idx',
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='privatemessage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='privatemessagebox',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='privatemessagebox',
            unique_together={('message', 'owner')},
        ),
    ]
