# Generated by Django 5.2.12 on 2026-04-06 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0023_alter_quotereference_quoted_username'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='quotereference',
            new_name='forum_quote_source__6f994d_idx',
            old_name='forum_quote_source__97bdf8_idx',
        ),
        migrations.RenameIndex(
            model_name='quotereference',
            new_name='forum_quote_quoted__a2e86e_idx',
            old_name='forum_quote_quoted__7e9bdf_idx',
        ),
        migrations.RenameIndex(
            model_name='quotereference',
            new_name='forum_quote_post_id_e66dc2_idx',
            old_name='forum_quote_post_id_d2b179_idx',
        ),
    ]
