# Generated by Django 5.2.12 on 2026-04-07 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0028_poll_polloption_pollvote'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='poll',
            new_name='forum_polls_is_clos_05d262_idx',
            old_name='forum_polls_is_clos_7ce5f8_idx',
        ),
        migrations.RenameIndex(
            model_name='poll',
            new_name='forum_polls_is_arch_5f177f_idx',
            old_name='forum_polls_is_arch_7bf6e1_idx',
        ),
        migrations.RenameIndex(
            model_name='pollvote',
            new_name='forum_poll__poll_id_81fc7b_idx',
            old_name='forum_poll__poll_id_259b9e_idx',
        ),
        migrations.RenameIndex(
            model_name='pollvote',
            new_name='forum_poll__option__09c41b_idx',
            old_name='forum_poll__option__c25ca5_idx',
        ),
        migrations.RenameIndex(
            model_name='postsearchindex',
            new_name='forum_post__forum_i_4b3ffa_idx',
            old_name='forum_post_s_forum_i_a3ec7a_idx',
        ),
        migrations.RenameIndex(
            model_name='postsearchindex',
            new_name='forum_post__topic_i_55660c_idx',
            old_name='forum_post_s_topic_i_b23f1e_idx',
        ),
        migrations.RenameIndex(
            model_name='postsearchindex',
            new_name='forum_post__author__9e7506_idx',
            old_name='forum_post_s_author__d38d66_idx',
        ),
    ]
