# Generated by Django 5.2.12 on 2026-04-07 22:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0034_user_mark_all_read_at_topicreadstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='IgnoredUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'forum_ignored_users',
            },
        ),
        migrations.RenameIndex(
            model_name='postlike',
            new_name='forum_post__user_id_f2c63f_idx',
            old_name='forum_post__user_id_604e7d_idx',
        ),
        migrations.RenameIndex(
            model_name='postlike',
            new_name='forum_post__post_id_d38f0e_idx',
            old_name='forum_post__post_id_34afdd_idx',
        ),
        migrations.RenameIndex(
            model_name='postsearchindex',
            new_name='forum_post__has_lin_ff48d5_idx',
            old_name='forum_post__has_lin_44be58_idx',
        ),
        migrations.RenameIndex(
            model_name='postsearchindex',
            new_name='forum_post__has_you_f2a27d_idx',
            old_name='forum_post__has_you_6a6da5_idx',
        ),
        migrations.RenameIndex(
            model_name='topicparticipant',
            new_name='forum_topic_topic_i_c5f821_idx',
            old_name='forum_topic_topic_id_b7e22c_idx',
        ),
        migrations.RenameIndex(
            model_name='topicparticipant',
            new_name='forum_topic_user_id_b166f9_idx',
            old_name='forum_topic_user_id_2dfcae_idx',
        ),
        migrations.RenameIndex(
            model_name='topicreadstate',
            new_name='forum_topic_user_id_343d59_idx',
            old_name='forum_topic_user_id_114d70_idx',
        ),
        migrations.RenameIndex(
            model_name='topicreadstate',
            new_name='forum_topic_topic_i_732d0e_idx',
            old_name='forum_topic_topic_id_0c3eca_idx',
        ),
        migrations.AddField(
            model_name='ignoreduser',
            name='ignored_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ignored_by_users_rel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ignoreduser',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ignored_users_rel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='ignoreduser',
            index=models.Index(fields=['owner'], name='forum_ignor_owner_i_9ab11e_idx'),
        ),
        migrations.AddIndex(
            model_name='ignoreduser',
            index=models.Index(fields=['ignored_user'], name='forum_ignor_ignored_0c5859_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ignoreduser',
            unique_together={('owner', 'ignored_user')},
        ),
    ]
