# Generated by Django 5.2.12 on 2026-04-07 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0035_ignoreduser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='last_post_at_gray',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='last_post_at_normal',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='last_post_gray_author_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='last_post_normal_author_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
