# Generated by Django 5.2.12 on 2026-04-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0037_morphform'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='morphform',
            new_name='forum_morph_form_no_627cb1_idx',
            old_name='forum_morph_form_norm_idx',
        ),
        migrations.RenameIndex(
            model_name='morphform',
            new_name='forum_morph_lemma_n_0eff89_idx',
            old_name='forum_morph_lemma_fam_idx',
        ),
        migrations.AlterField(
            model_name='morphform',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
