# Generated by Django 5.2.12 on 2026-04-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0039_morphsuffix'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='morphsuffix',
            new_name='forum_morph_suffix__36918a_idx',
            old_name='forum_morph_suffix_lookup_idx',
        ),
        migrations.AlterField(
            model_name='morphsuffix',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
