# Generated by Django 5.2.12 on 2026-04-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0041_morphform_nom_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='access_level',
            field=models.SmallIntegerField(choices=[(0, 'Public'), (1, 'Registered only'), (2, 'Admin only'), (3, 'Admin + Blogger')], default=0, help_text='Who can see this forum (phpBB visibility_class)'),
        ),
    ]
