# Generated by Django 5.2.12 on 2026-04-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0042_alter_forum_access_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.SmallIntegerField(choices=[(0, 'Użytkownik'), (1, 'Moderator'), (2, 'Administrator')], db_index=True, default=0, help_text='0=użytkownik, 1=moderator, 2=administrator. Root jest osobnym kontem (is_root).'),
        ),
    ]
