# Generated by Django 5.2.12 on 2026-04-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0043_user_role'),
    ]

    operations = [
        # Drop unique_together constraint if it exists.
        # Some DBs may have had it removed already (e.g. by import_morph_csv --clear),
        # so we use IF EXISTS via SeparateDatabaseAndState to avoid "0 constraints found".
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE forum_morph_form "
                        "DROP CONSTRAINT IF EXISTS "
                        "forum_morph_form_form_norm_lemma_norm_family_id_6633bba1_uniq"
                    ),
                    reverse_sql="",
                ),
            ],
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='morphform',
                    unique_together=set(),
                ),
            ],
        ),
        migrations.AddField(
            model_name='morphform',
            name='pk',
            field=models.CompositePrimaryKey('form_norm', 'lemma_norm', 'family_id', blank=True, editable=False, primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='morphform',
            name='id',
        ),
        # Django's CompositePrimaryKey doesn't emit ADD PRIMARY KEY DDL — add it manually.
        # Some DBs may already have this PK (e.g. after import_morph_csv --clear), so guard.
        migrations.RunSQL(
            sql="""
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint
                        WHERE conrelid = 'forum_morph_form'::regclass AND contype = 'p'
                    ) THEN
                        ALTER TABLE forum_morph_form
                            ADD PRIMARY KEY (form_norm, lemma_norm, family_id);
                    END IF;
                END$$;
            """,
            reverse_sql="ALTER TABLE forum_morph_form DROP CONSTRAINT IF EXISTS forum_morph_form_pkey;",
        ),
    ]
