# Generated by Django 5.2.12 on 2026-04-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0043_user_role'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='morphform',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='morphform',
            name='pk',
            field=models.CompositePrimaryKey('form_norm', 'lemma_norm', 'family_id', blank=True, editable=False, primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='morphform',
            name='id',
        ),
        # Django's CompositePrimaryKey doesn't emit ADD PRIMARY KEY DDL — add it manually.
        migrations.RunSQL(
            sql="ALTER TABLE forum_morph_form ADD PRIMARY KEY (form_norm, lemma_norm, family_id);",
            reverse_sql="ALTER TABLE forum_morph_form DROP CONSTRAINT IF EXISTS forum_morph_form_pkey;",
        ),
    ]
