# Generated by Django 5.2.12 on 2026-04-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0044_morphform_composite_pk'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='poll_options_soft_max',
            field=models.PositiveSmallIntegerField(default=32, help_text='Miękki limit opcji ankiety (max = twardy limit z settings POLL_OPTIONS_HARD_MAX, domyślnie 64).'),
        ),
    ]
