# Generated by Django 5.2.12 on 2026-04-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0045_siteconfig_poll_options_soft_max'),
    ]

    operations = [
        migrations.AddField(
            model_name='polloption',
            name='category',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
