# Generated by Django 5.2.12 on 2026-04-11 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0046_polloption_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='poll_options_soft_max',
            field=models.PositiveSmallIntegerField(default=50, help_text='Miękki limit opcji ankiety (max = twardy limit z settings POLL_OPTIONS_HARD_MAX, domyślnie 64).'),
        ),
    ]
