# Generated by Django 5.2.12 on 2026-04-11 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0047_siteconfig_poll_soft_max_50'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=31, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username_normalized',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Lowercase, no diacritics, alphanumeric only. Used for uniqueness checks.', max_length=31),
        ),
    ]
