# Generated by Django 5.2.12 on 2026-04-11 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0048_username_max_length_31'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpamDomain',
            fields=[
                ('domain', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('spam', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'forum_spam_domain',
            },
        ),
    ]
