# Generated by Django 5.2.12 on 2026-04-11 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0049_spam_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='spamdomain',
            name='added_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
