# Generated by Django 5.2.12 on 2026-04-11 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0051_user_banned_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_processing',
            field=models.BooleanField(default=False, help_text='Locked during rename/delete — blocks posting, quoting, editing.'),
        ),
    ]
