# Generated by Django 5.2.12 on 2026-04-11 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0052_user_is_processing'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceAllowedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=31, unique=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'forum_maintenance_allowed_user',
            },
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='maintenance_message',
            field=models.TextField(blank=True, default='', help_text='Komunikat wyświetlany podczas przerwy technicznej.'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='site_mode',
            field=models.CharField(choices=[('normal', 'Normalny'), ('readonly', 'Tylko do odczytu'), ('closed', 'Zamknięte (tylko lista serwisowa)')], default='normal', max_length=10),
        ),
    ]
