# Generated by Django 5.2.12 on 2026-04-12 10:53

from django.db import migrations, models


def rename_site_modes(apps, schema_editor):
    SiteConfig = apps.get_model("board", "SiteConfig")
    SiteConfig.objects.filter(site_mode="normal").update(site_mode="production")
    SiteConfig.objects.filter(site_mode="closed").update(site_mode="maintenance")


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0054_user_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfig',
            name='reset_mode',
        ),
        migrations.AddField(
            model_name='post',
            name='is_temporary',
            field=models.BooleanField(db_index=True, default=False, help_text='Temporary post — excluded from export, deleted on mode cleanup.'),
        ),
        migrations.AddField(
            model_name='topic',
            name='is_temporary',
            field=models.BooleanField(db_index=True, default=False, help_text='Auto-managed: True when all posts are temporary, False when any post is permanent.'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_temporary',
            field=models.BooleanField(default=False, help_text='Temporary account created during maintenance/beta — deleted on mode cleanup.'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='site_mode',
            field=models.CharField(choices=[('production', 'Produkcja'), ('readonly', 'Tylko do odczytu'), ('maintenance', 'Serwis (bramka + tymczasowe konta)'), ('beta', 'Beta (otwarte + tymczasowe konta)')], default='production', max_length=12),
        ),
        migrations.RunPython(rename_site_modes, migrations.RunPython.noop),
    ]
