# Generated by Django 5.2.12 on 2026-04-12 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0055_operating_modes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfig',
            name='show_switch_link',
        ),
    ]
