# Generated by Django 5.2.12 on 2026-04-13 13:36

from django.db import migrations, models


def recompute_username_normalized(apps, schema_editor):
    """
    Recompute username_normalized from the current username for every user.
    After import_from_sfinia runs with new_name (e.g. ja → ja_1 → norm: ja1),
    usernames are already correct and this step produces unique normalised values.
    """
    import unicodedata
    _MANUAL = {'ł': 'l', 'Ł': 'l', 'ø': 'o', 'Ø': 'o', 'æ': 'a', 'Æ': 'a'}

    def normalize(username):
        u = ''.join(_MANUAL.get(c, c) for c in username)
        u = unicodedata.normalize('NFKD', u)
        return ''.join(c for c in u.lower() if c.isalnum())

    User = apps.get_model("board", "User")
    batch = []
    for user in User.objects.only("pk", "username", "username_normalized"):
        norm = normalize(user.username)
        if user.username_normalized != norm:
            user.username_normalized = norm
            batch.append(user)
        if len(batch) >= 500:
            User.objects.bulk_update(batch, ["username_normalized"])
            batch.clear()
    if batch:
        User.objects.bulk_update(batch, ["username_normalized"])


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0057_remove_is_ghost_is_banned'),
    ]

    operations = [
        migrations.RunPython(recompute_username_normalized, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='username_normalized',
            field=models.CharField(blank=True, default='', help_text='Lowercase, no diacritics, alphanumeric only. Used for uniqueness checks.', max_length=31, unique=True),
        ),
    ]
