# Generated by Django 5.2.12 on 2026-04-13 16:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0058_unique_username_normalized'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='feature',
            field=models.IntegerField(choices=[(0, 'Plain'), (1, 'Poll'), (2, 'Checklist')], default=0),
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_user_proposals', models.BooleanField(default=True)),
                ('default_sort', models.CharField(choices=[('upvotes', 'Upvotes'), ('priority', 'Priority'), ('date', 'Date'), ('status', 'Status')], default='upvotes', max_length=10)),
                ('is_closed', models.BooleanField(default=False)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('topic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='board.topic')),
            ],
            options={
                'db_table': 'forum_checklists',
            },
        ),
        migrations.CreateModel(
            name='ChecklistCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(default='#6c757d', max_length=7)),
                ('order', models.IntegerField(default=0)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='board.checklist')),
            ],
            options={
                'db_table': 'forum_checklist_categories',
                'ordering': ['order', 'id'],
                'unique_together': {('checklist', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_label', models.CharField(blank=True, default='', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Rejected'), (2, 'New'), (3, 'In progress'), (4, 'Done'), (5, "Won't fix"), (6, 'Duplicate')], default=2)),
                ('priority', models.IntegerField(blank=True, choices=[(1, 'Critical'), (2, 'Important'), (3, 'Minor'), (4, 'Planned')], null=True)),
                ('rejection_reason', models.CharField(blank=True, default='', max_length=500)),
                ('upvote_count', models.IntegerField(default=0)),
                ('anon_upvote_count', models.IntegerField(default=0)),
                ('comment_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status_changed_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_items', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='board.checklistcategory')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='board.checklist')),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='board.checklistitem')),
                ('status_changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'forum_checklist_items',
            },
        ),
        migrations.CreateModel(
            name='ChecklistComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_label', models.CharField(blank=True, default='', max_length=30)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_comments', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='board.checklistitem')),
            ],
            options={
                'db_table': 'forum_checklist_comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistUpvote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upvotes', to='board.checklistitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_upvotes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'forum_checklist_upvotes',
            },
        ),
        migrations.AddIndex(
            model_name='checklistitem',
            index=models.Index(fields=['checklist', 'status'], name='forum_check_checkli_b9f0ed_idx'),
        ),
        migrations.AddIndex(
            model_name='checklistitem',
            index=models.Index(fields=['checklist', '-upvote_count'], name='forum_check_checkli_8e9a25_idx'),
        ),
        migrations.AddIndex(
            model_name='checklistitem',
            index=models.Index(fields=['checklist', 'created_at'], name='forum_check_checkli_bc656d_idx'),
        ),
        migrations.AddIndex(
            model_name='checklistcomment',
            index=models.Index(fields=['item', 'created_at'], name='forum_check_item_id_453a3b_idx'),
        ),
        migrations.AddIndex(
            model_name='checklistupvote',
            index=models.Index(fields=['item'], name='forum_check_item_id_9ff633_idx'),
        ),
        migrations.AddIndex(
            model_name='checklistupvote',
            index=models.Index(fields=['user'], name='forum_check_user_id_c1a5a2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='checklistupvote',
            unique_together={('item', 'user')},
        ),
    ]
