# Generated by Django 5.2.12 on 2026-04-13 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0059_checklist_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklistitem',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='checklistitem',
            index=models.Index(fields=['checklist', 'order'], name='forum_check_checkli_aaf882_idx'),
        ),
    ]
