# Generated by Django 5.2.12 on 2026-04-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0066_blocked_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderationwindow',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
