# Generated by Django 5.2.12 on 2026-05-15 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0076_post_merge_log_updated_by_no_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('access_level', models.SmallIntegerField(choices=[(0, 'Public'), (1, 'Registered only'), (2, 'Admin only'), (3, 'Admin + Blogger')], default=0, help_text='Who can see this board (phpBB visibility_class)')),
                ('archive_level', models.SmallIntegerField(choices=[(0, 'Normal'), (1, 'Soft darkweb (spam=1 users)'), (2, 'Hard darkweb (Krowa clones, Więzienie etc.)')], default=0, help_text='Archive content sensitivity level')),
                ('topic_count', models.PositiveIntegerField(default=0)),
                ('post_count', models.PositiveIntegerField(default=0)),
                ('last_post_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'forum_boards',
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='forum',
            name='blog_of',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='last_post',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='moderators',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='section',
        ),
        migrations.RemoveField(
            model_name='postsearchindex',
            name='forum',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='forum',
        ),
        migrations.RemoveConstraint(
            model_name='postreport',
            name='unique_report_per_user',
        ),
        migrations.RemoveIndex(
            model_name='postsearchindex',
            name='forum_post__forum_i_4b3ffa_idx',
        ),
        migrations.RemoveIndex(
            model_name='topic',
            name='forum_topic_forum_i_502c1f_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='forum_notif_recipie_b551f9_idx',
            old_name='notif_recipient_unread_idx',
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='postreport',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='postreport',
            name='reporter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='postreport',
            unique_together={('post', 'reporter')},
        ),
        migrations.AddField(
            model_name='board',
            name='blog_of',
            field=models.ForeignKey(blank=True, help_text='Właściciel bloga — może edytować każdy post w tym dziale jak moderator.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_boards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='board',
            name='last_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='board.post'),
        ),
        migrations.AddField(
            model_name='board',
            name='moderators',
            field=models.ManyToManyField(blank=True, related_name='moderated_boards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='board',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subboards', to='board.board'),
        ),
        migrations.AddField(
            model_name='board',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boards', to='board.section'),
        ),
        migrations.AddField(
            model_name='postsearchindex',
            name='board',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='search_posts', to='board.board'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='board',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='board.board'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='postsearchindex',
            index=models.Index(fields=['board', 'created_at'], name='forum_post__board_i_9e005a_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['board', '-topic_type', '-last_post_at'], name='forum_topic_board_i_8c6925_idx'),
        ),
        migrations.DeleteModel(
            name='Forum',
        ),
    ]
